FROM tomcat:8.5.49-jdk8-openjdk

MAINTAINER calvinmrewa@gmail.com
ADD sampleLogin.war/usr/local/tomcat/webapps/
ADD sample.war /usr/local/tomcat/webapps

EXPOSE 8080

CMD ["catalina.sh", "run"]